import Head from "next/head";
import App from "../components/App";
import { Box } from "@chakra-ui/react";

export default function Home() {
	return (
		<Box w='full'>
			<Head>
				<title>Tourist Mountain</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<App />
		</Box>
	);
}
